### ISSUE TITLE
Rename to `wasi-threads`?

### ISSUE THREAD

**Issue by abrown** [WebAssembly/wasi-threads#4]
I have only ever referred to this proposal as "WASI threads" in conversations I've had about this. I'm not sure how much value the "native" provides in the name (why was that added in the first place?). Could we discuss renaming this repository to `wasi-threads`?

**Comment by AlexEne** [comment]
We can do it, I think wasi part already differentiates it from the existing "threads" (that are basically atomic operations)

**Comment by sbc100** [comment]
I think the "native" parts comes from the JS thread API where the current state of the art is "threads as JS workers".   There is a proposal to allow wasm native threads which would allow for pure-wasm threads. 

This repo is more about creating a wasi API for threads .. and the resulting threads won't be "native" to wasm in that they will be greated via some kind of "clone" API which is imported .. so I agree the "native" part is wrong here.

**Comment by linclark** [comment]
Done!
