### ISSUE TITLE
Handling data section from multiple instantiations of module

### ISSUE THREAD

**Issue by anuraaga** [WebAssembly/wasi-threads#44]
I have been playing with wasi-sdk threads support to compile code using pthread_mutex for use from multiple host threads. Note, I am not currently looking at spawning threads with Wasm but using a Wasm module from multiple threads in a safe way - I think this spec might be mostly about spawning, but I was directed here for this use case as well.

Some slightly related context: https://github.com/WebAssembly/wasi-sdk/issues/328

Through that I learned of the one instance-per-thread model, which at first wasn't what I was expecting. I understand some of the reasons for going with it, especially the use of wasm globals like `__stack_pointer` and `__tls_base` in the operation of compiled code.

Reading through this spec and the WebAssembly threads spec, one point I haven't found clarified is handling of data sections (let me know if I just missed it!). Data sections define blobs that are copied into `memory` at certain offsets - it seems like if a module is importing shared memory, each time it is instantiated, that section of the shared memory will get reset. Is there any documentation on how data sections should be handled when instantiating modules that import shared memory? Is there an expectation that compilers like LLVM make sure that data sections are only used when they can be idempotent across multiple instantiations, and otherwise code needs to be generated to do it safely?

**Comment by anuraaga** [comment]
Looking at some compiled wasm some more, I found `__wasm_init_memory`, which seems to copy-in the data sections guarded by a mutex of sorts. So I guess that means that indeed, the expectation is that compilers only generate data sections that they use in memory initialization in a thread-safe way. If that sounds right, then this issue can be closed.

```
(func $__wasm_init_memory (type 1)
    block  ;; label = @1
      block  ;; label = @2
        block  ;; label = @3
          i32.const 1212
          i32.const 0
          i32.const 1
          i32.atomic.rmw.cmpxchg
          br_table 0 (;@3;) 1 (;@2;) 2 (;@1;)
        end
        i32.const 1024
        i32.const 1024
        global.set $__tls_base
        i32.const 0
        i32.const 112
        memory.init $.tdata
        i32.const 1136
        i32.const 0
        i32.const 4
        memory.init $.rodata
        i32.const 1140
        i32.const 0
        i32.const 4
        memory.init $.data
        i32.const 1144
        i32.const 0
        i32.const 68
        memory.fill
        i32.const 1212
        i32.const 2
        i32.atomic.store
        i32.const 1212
        i32.const -1
        memory.atomic.notify
        drop
        br 1 (;@1;)
      end
      i32.const 1212
      i32.const 1
      i64.const -1
      memory.atomic.wait32
      drop
    end
    data.drop $.rodata
    data.drop $.data)
```

**Comment by sbc100** [comment]
Yes, that is correct, its up the module to ensure that segments are only loaded once.

In the llvm case its the linker (wasm-ld) that generates this startup code: https://github.com/llvm/llvm-project/blob/3b6f7e45a20990fdbc2b43dc08457fc79d53bd39/lld/wasm/Writer.cpp#L1201-L1208

Assuming that answers you question, I guess this issue can be closed?
