### ISSUE TITLE
Guest function to setup a child thread stack without executing a start func

### ISSUE THREAD

**Issue by anuraaga** [WebAssembly/wasi-threads#45]
As many know, I've been working on using threads support to switch from a global lock across all invocations into a Wasm module to be able to invoke a function within Wasm concurrently from multiple host threads, with the Wasm doing fine-grained locking only where needed. At first I thought just having atomics support would be enough but at the end of the rabbit hole I've found that stack/tls management within pthread_create itself is important for having concurrently executing Wasm modules when compiled from LLVM.

In my case, it is a Go library called possibly from multiple goroutines - the library itself doesn't spawn any threads. It would still be great to be able to setup C threads to map to calling goroutines and have concurrent access, but without pthread_create actually executing the thread as the host would still control execution. Basically, in each host goroutine, the flow could look like

- Initialize new child module
- Lock in host to prevent stack corruption within wasi_new_thread itself
- Call wasi_new_thread(int tid) from host in child module
  - wasi_new_thread allocates stack/tls from current globals stack pointer / tls base and then sets globals to the new values, sets tid to passed in value. Then it returns, without calling any function
- Unlock in host
- Call any number of guest functions. The globals have been set to the copied stack/tls so will affect the parent module's stack/tls
- Call wasi_end_thread() from host in child module
  - wasi_end_thread frees allocated stack/tls and resets globals (technically reset is not useful since this only makes sense when getting ready to delete the child itself, freeing from the shared malloc is important though)

Is something like this reasonable to allow concurrent access to Wasm from a host, or is there any other approach that might work without a new API?

**Comment by anuraaga** [comment]
I tried prototyping something here

https://github.com/anuraaga/go-re2/blob/threads-crazy/internal/cre2/thread.c#L60

I ended up using two guest entry points since it seemed like it might be a good idea to stick to an asm trampoline for setting the globals, though with care it could possibly be in one. I haven't done a detailed examination of the stability / validity of this but thought it could help illustrate the idea.

**Comment by abrown** [comment]
Ok, I spent some time today trying to understand "why" &mdash; let's see if I get this right: you want to have an alternate regex library in Go and want to distribute this library as WebAssembly (for portability, I guess?). Because the regex library can be concurrently called from multiple goroutines and you don't want concurrent invocations to be needlessly blocked by a global lock, you are considering spawning new threads for each invocation (?) and performing some host-side locking to try to keep things safe. Here's what I don't get: why not compile the Wasm module once and create new, cheap instances for each invocation of the library?

Maybe I don't understand something here but it seems like wasi-threads is going to add a whole new level of complexity. Also, I could have totally misread the project so forgive me if that's the case! I understand this to be a "do regex in native Go" problem but if you're actually trying a "do regex in Go compiled to Wasm," you might be more interested in [wasi-pattern-match](https://github.com/WebAssembly/wasi-pattern-match/).

**Comment by anuraaga** [comment]
> you are considering spawning new threads for each invocation (?) and performing some host-side locking to try to keep things safe. 

To be more precise, I would use a pool of wasm-side threads but should be the same idea in principle.

> Here's what I don't get: why not compile the Wasm module once and create new, cheap instances for each invocation of the library?

I'm not sure if this is in the context of shared memory / atomics or not.

If shared / atomics, then while instantiation is cheap, the modules will not function correctly since they all have globals like stack pointer to the same location in memory and collide. The ABIs in this proposal seem to be positioned for being the entry point for managing these globals, which wasi-libc uses to set them up to not collide.

If not using shared/atomics, the answer is that it's not a cheap instance as the memory usage per instance for things like .rodata is huge, memory usage and instantiation time would be prohibitive. And since regex is stateful (need to compile once, run many), the module needs to be reused after compilation. Currently go-re2 uses an instance per compiled regex with a lock per instance. This allows some concurrency when using multiple regex at the same time but it's not that great and still does use a lot of memory. I'm hoping to take advantage of threads to remove this overhead, hopefully bringing the Wasm codepath to have no significant tradeoffs vs cgo. 

> Maybe I don't understand something here but it seems like wasi-threads is going to add a whole new level of complexity. 

It seems the proposal is entirely about starting threads from the guest but not the host. If that's the scope then it is what it is. But given embedding a guest in a host as a sort of plugin seems like a main use case for WASI, not just self-contained apps, it seems like it would be nice if possible that host-started threads are also supported.

**Comment by abrown** [comment]
> It seems the proposal is entirely about starting threads from the guest but not the host. If that's the scope then it is what it is.

Yeah, I think that statement is correct. It might be possible to hack together something like what you suggested originally by (a) immediately `wait`-ing in the start function or (b) hacking something C-side, maybe with a custom wasi-libc, to get the child stack you're looking for. It feels to me like the approach might be a bit unconventional but that you might be able to make something work, but I don't think you need changes to the wasi-threads specification to do so. And even if you did, it's debatable whether that kind of thing is in scope here. I'll close this but feel free to reopen if I misunderstood something.
